
trigger:
- debug

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    docker run -d \
    --net host \
    --name ipfs \
    ipfs/go-ipfs:latest daemon --enable-pubsub-experiment
  displayName: 'Run ipfs daemon'

- script: |
    docker run \
    --net host \
    --name orbit-db-http-api \
    -e IPFS_HOST='localhost' \
    -e LOG='DEBUG' \
    phillmac/orbit-db-http-api-dev:debug src/cli.js api
  displayName: 'Run orbit-db-http-api-container'