# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- debug

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'OrbitDB Docker Hub'
        repository: 'phillmac/orbit-db-http-api-dev'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          debug
          'debug-$(tag)'
    - script: docker run --rm phillmac/orbit-db-http-api-dev:debug src/cli.js --version
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'OrbitDB Docker Hub'
        repository: 'phillmac/orbit-db-http-api-dev'
        command: 'push'
        tags: |
          'debug-$(tag)'
    - task: TriggerBuild@3
      inputs:
        definitionIsInCurrentTeamProject: false
        tfsServer: 'https://phillmac.visualstudio.com'
        teamProject: '804fe699-2025-46ad-b3c1-29bd8f6e974d'
        buildDefinition: 'phillmac.orbit-db-http-api-tests'
        queueBuildForUserThatTriggeredBuild: false
        ignoreSslCertificateErrors: false
        useSameSourceVersion: false
        useCustomSourceVersion: false
        useSameBranch: false
        branchToUse: 'master'
        waitForQueuedBuildsToFinish: true
        waitForQueuedBuildsToFinishRefreshTime: '30'
        failTaskIfBuildsNotSuccessful: true
        cancelBuildsIfAnyFails: false
        treatPartiallySucceededBuildAsSuccessful: false
        downloadBuildArtifacts: false
        storeInEnvironmentVariable: false
        buildParameters: 'API_Image_Branch: debug-$(tag)'
        authenticationMethod: 'Personal Access Token'
        password: '$(PiplinesPAT)'
        enableBuildInQueueCondition: false
        dependentOnSuccessfulBuildCondition: false
        dependentOnFailedBuildCondition: false
        checkbuildsoncurrentbranch: false
        failTaskIfConditionsAreNotFulfilled: false
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'OrbitDB Docker Hub'
        repository: 'phillmac/orbit-db-http-api-dev'
        command: 'push'
        tags: |
          debug
