FROM mcr.microsoft.com/windows/servercore:ltsc2019 as installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]

ARG NODE_VERSION="v12.13.1"

RUN powershell -NoProfile -Command " \
    Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing """https://nodejs.org/dist/$Env:NODE_VERSION/node-$Env:NODE_VERSION-win-x64.zip"""; \
    Expand-Archive nodejs.zip -DestinationPath C:\; \
    Rename-Item """C:\node-$Env:NODE_VERSION-win-x64""" c:\nodejs; \
    Invoke-WebRequest """https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/MinGit-2.24.0.2-64-bit.zip""" -OutFile MinGit.zip; \
    Expand-Archive c:\MinGit.zip -DestinationPath c:\MinGit; \
"

FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=installer /nodejs /MinGit /
ENV PATH="$WindowsPATH;C:\nodejs;C:\MinGit\cmd"

RUN npm config set registry https://registry.npmjs.org/

WORKDIR /orbit-db-http-api

# install and cache app dependencies
COPY package.json /orbit-db-http-api/package.json

RUN npm install

# add app
COPY . /orbit-db-http-api

# start app
ENTRYPOINT ["node", "src/cli.js"]
