FROM mcr.microsoft.com/windows/servercore:ltsc2019 as installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]

ARG NODE_VERSION="v12.13.1"

RUN powershell -NoProfile -Command " \ 
    Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing """https://nodejs.org/dist/$Env:NODE_VERSION/node-$Env:NODE_VERSION-win-x64.zip"""; \
    Expand-Archive nodejs.zip -DestinationPath C:\; \
    Rename-Item """C:\node-$Env:NODE_VERSION-win-x64""" c:\nodejs \
"

FROM mcr.microsoft.com/windows/nanoserver:1803

WORKDIR /nodejs
COPY --from=installer /nodejs/ .
RUN SETX PATH C:\nodejs
RUN npm config set registry https://registry.npmjs.org/

WORKDIR /orbit-db-http-api

# install and cache app dependencies
COPY package.json /orbit-db-http-api/package.json

RUN npm install

# add app
COPY . /orbit-db-http-api

# start app
ENTRYPOINT ["node", "src/cli.js"]
